### ISSUE TITLE
Convert dict/ into a Simple List of Words

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/wordrow#61]
Suggested by @mlutze : replace the *Hunspell* dictionaries with a simple list of all words. This has the following benefits:

1. This will make it easier for people to create pull requests that add/remove words from the dictionary.
2. This will make building the entire game much faster.

**Tasks**

- [ ] Turn *game_gen/dict.h* into a separate *Hunspell* dictionary exploder: it generates all words from the dictionary, sorts them and then prints them out (without duplicates) 
- [ ] Turn *game_gen/main.cpp* into a simple *read-file-and-populate-an-Anatree*.
- [ ] Convert *dict/* into a simple list of words.
